# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico
github: [metadata]

# Content configuration version
version: 2

# Personal info
name: Batuhan Usluel
title: CS + Econ at UIUC
email: me@batuhanusluel.com
website: http://batuhanusluel.com/

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  BatuhanUsluel
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: batuhanusluel
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Pdf Download
  icon: far fa-file-pdf
  url: https://github.com/BatuhanUsluel/BatuhanUsluel.github.io/raw/master/pdf/cv.pdf

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Batuhan and I'm a Computer Science + Econ student at UIUC.

content:

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: CME Group
        link: cmegroup.com
        sub_title: Software Engineer Intern
        caption: May 2022 - Aug 2022
        description: | # this will include new lines to allow paragraphs
          - Wrote an application in Java for real time testing of their matching engine.
          - Replaced periodic manual checks for errors with an automated system.
          - Pinpoints exact message where mistakes started occurring.
          - Deployed Kafka instance to listen to engine and relay messages for performance and reliability reasons.


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: University of Illinois at Urbana-Champaign
        caption: "January 2022 - Present (Expected Graduation: May 2024)"
        sub_title: |
          Computer Science + Econ

          GPA: 4.0
        # quote: >
        #   GPA: 4.0
        # description: | # this will include new lines to allow paragraphs
        #   TEMP
      - layout: top-middle
        title: Purdue University
        caption: August 2020 - December 2021
        sub_title: Computer Science
        quote: >
          GPA: 3.56
        # description: | # this will include new lines to allow paragraphs
        #   TEMP

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Algorithmic Support and Resistance | Python
        link: https://github.com/BatuhanUsluel/Algorithmic-Support-and-Resistance
        description: | # this will include new lines to allow paragraphs
          - Coded a project to find reversal points on stock prices.
          - Detects reversal points by finding clusters of local min and max points.
          - Retrieves stock price history through Yahoo Finance, displayed charts with reversal points marked.
          - Well received by people, has  190+ stars and 30+ forks on GitHub.
      
      - layout: top-middle
        title: Arbitrage Bot | Python
        link: https://github.com/BatuhanUsluel/ArbitrageBot
        description: | # this will include new lines to allow paragraphs
          - Developed a trading bot for cryptocurrencies that took advantage of pricing discrepancies between exchanges.
          - Connected to exchanges via their APIs, fetching prices and checking if there were profitable trades available.
          - Automatically executed trades when profitable ones were detected.
          - Open sourced on GitHub, received 140+ stars and 60+ forks.



# Footer
# footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
