# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Batuhan Usluel
title: CS + Econ at UIUC
# email: brett.h@email.co.uk
# website: https://github.com/BatuhanUsluel/

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  BatuhanUsluel
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: batuhanusluel
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Batuhan and I'm a Computer Science + Econ student at UIUC.
  I'm passinate about both <mark>technology</mark> and <mark>finance</mark>

content:

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: CME Group
        link: cmegroup.com
        # link_text: boringcompany.com
        sub_title: Software Engineer Intern
        caption: May 2022 - Aug 2022
        quote: >
          TEMP
        description: | # this will include new lines to allow paragraphs
          TEMP

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Illinois at Urbana-Champaign
        caption: "January 2022 - Present (Expected Graduation: May 2024)"
        sub_title: Computer Science + Econ
        quote: >
          TEMP
        description: | # this will include new lines to allow paragraphs
          TEMP
      - layout: left
        title: Purdue University
        caption: August 2020 - December 2021
        sub_title: Computer Science
        quote: >
          TEMP
        description: | # this will include new lines to allow paragraphs
          TEMP

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        # link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          TEMP
        description: | # this will include new lines to allow paragraphs
          TEMP

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
