# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico
github: [metadata]

# Content configuration version
version: 2

# Personal info
name: Batuhan Usluel
title: CS + Econ at UIUC
email: me@batuhanusluel.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  BatuhanUsluel
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: batuhanusluel
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Pdf Download
  icon: far fa-file-pdf
  url: https://github.com/BatuhanUsluel/BatuhanUsluel.github.io/raw/master/pdf/cv.pdf

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Batuhan and I'm a Computer Science + Econ student at UIUC.

content:

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: CME Group
        link: cmegroup.com
        sub_title: Software Engineer Intern
        caption: May 2022 - Aug 2022
        description: | # this will include new lines to allow paragraphs
          - Wrote an application in Java for real time testing of their matching engine.
          - Replaced periodic manual checks for errors with an automated system.
          - Pinpoints exact message where mistakes started occurring.
          - Deployed Kafka instance to listen to engine and relay messages for performance and reliability reasons.


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: University of Illinois at Urbana-Champaign
        caption: |
          January 2022 - Present (Expected Graduation: May 2024)
            
          GPA: 4.0
        sub_title: Computer Science + Econ
        # quote: >
        #   GPA: 4.0
        # description: | # this will include new lines to allow paragraphs
        #   TEMP
      - layout: top-middle
        title: Purdue University
        caption: August 2020 - December 2021
        sub_title: Computer Science
        quote: >
          GPA: 3.56
        # description: | # this will include new lines to allow paragraphs
        #   TEMP

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Algorithmic Support and Resistance | Python
        link: https://github.com/BatuhanUsluel/Algorithmic-Support-and-Resistance
        description: | # this will include new lines to allow paragraphs
          - Coded a project to find reversal points on stock prices.
          - Detects reversal points by finding clusters of local min and max points.
          - Retrieves stock price history through Yahoo Finance, displayed charts with reversal points marked.
          - Well received by people, has  190+ stars and 30+ forks on GitHub.
      
      - layout: top-middle
        title: Arbitrage Bot | Python
        link: https://github.com/BatuhanUsluel/ArbitrageBot
        description: | # this will include new lines to allow paragraphs
          - Developed a trading bot for cryptocurrencies that took advantage of pricing discrepancies between exchanges.
          - Connected to exchanges via their APIs, fetching prices and checking if there were profitable trades available.
          - Automatically executed trades when profitable ones were detected.
          - Open sourced on GitHub, received 140+ stars and 60+ forks.

      - layout: top-middle
        title: Trading Automator Bot | Java
        link: https://github.com/BatuhanUsluel/Trading-Automator-Bot
        description: | # this will include new lines to allow paragraphs
          - Created a GUI Application to trade cryptocurrencies. 
          - Has features such as Arbitrage, basic market making, back-testing and live trading simple TA Strategies, dollar-cost averaging, trailing stops, and more.
          - Supports dozens of different exchanges using the Xchange library.

      - layout: top-middle
        title: BTSplit | Python
        link: https://github.com/BatuhanUsluel/BTSplit
        description: | # this will include new lines to allow paragraphs
          - Coded a tool to manage large spreadsheet files due to the limitation of ~1 million rows in excel files.
          - Can split a larger file into many sheets or subfiles of various file types, adjusts formulas to point to new cells.
          - Supports different file types (.csv, .xlsx, .xls) and has many customizable settings.

      - layout: top-middle
        title: iDetect | Python
        link: https://devpost.com/software/idetect
        additional_links:
          - title:  ClassAttentionDetector
            icon: fab fa-github
            url: https://github.com/BatuhanUsluel/ClassAttentionDetector
        description: | # this will include new lines to allow paragraphs
          - Created a application to analyze video calls
          - Graphs out real-time graph of aggregate emotions over time
          - Done during iMAKE hackathon hosted by Illini Esports

      - layout: top-middle
        title: RMV Road Test Appointment Finder | Python
        additional_links:
          - title:  RMV Road Test Appointment Finder
            icon: fab fa-github
            url: https://github.com/BatuhanUsluel/RMV-Road-Test-Appointment-Finder
        description: | # this will include new lines to allow paragraphs
          - Regularly searches the RMV website for desired road test appointments
          - Notifies the user when an appointment is found

      - layout: top-middle
        title: Chrome Video Note Taker | JavaScript
        link: https://devpost.com/software/video-note-taker
        additional_links:
          - title: Chrome Video Note Taker
            icon: fab fa-github
            url: https://github.com/BatuhanUsluel/Chrome-Video-Note-Taker
        description: | # this will include new lines to allow paragraphs
          - Chrome extension that allows you to take notes as you are watching a video.
          - Can later on click on a note which opens up the video at the right timestamp.
          - Done during 'Hello World 2020' hackathon at Purdue.



# Footer
# footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
